### ISSUE TITLE
抛出了一个ApiException status': 3, 'title': '错误提示', 'message': '发生了错误(E)。\\n回到标题界面。

### ISSUE THREAD

**Issue by TsaiDuck** [AddOneSecondL/pcrjjc2-clanbattle#38]
这是在发送会战状态的时候控制台打印的错误信息，貌似是自定义的一个 ApiException ，下面是错误日志

[2023-12-24 12:56:27,354 会战推送] INFO: Message -1146330721 triggered status.
[2023-12-24 12:56:27,354] INFO in msghandler: Message -1146330721 triggered status.
pcrclient: /load/index api failed {'status': 3, 'title': '错误提示', 'message': '发生了错误(E)。\\n回到标题界面。'}
[2023-12-24 12:56:27,551 会战推送] ERROR: <class 'hoshino.modules.pcrjjc2-clanbattle.pcrclient.ApiException'> occured when status handling message -1146330721.
[2023-12-24 12:56:27,551] ERROR in msghandler: <class 'hoshino.modules.pcrjjc2-clanbattle.pcrclient.ApiException'> occured when status handling message -1146330721.
[2023-12-24 12:56:27,554 会战推送] ERROR: 发生了错误(E)。\n回到标题界面。
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\pcrjjc2-clanbattle\__init__.py", line 650, in status
    load_index = await client.callapi('/load/index', {'carrier': 'OPPO'})
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\pcrjjc2-clanbattle\pcrclient.py", line 173, in callapi
    raise ApiException(data['message'], data['status'])
hoshino.modules.pcrjjc2-clanbattle.pcrclient.ApiException: 发生了错误(E)。\n回到标题界面。
[2023-12-24 12:56:27,554] ERROR in msghandler: 发生了错误(E)。\n回到标题界面。
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\pcrjjc2-clanbattle\__init__.py", line 650, in status
    load_index = await client.callapi('/load/index', {'carrier': 'OPPO'})
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\pcrjjc2-clanbattle\pcrclient.py", line 173, in callapi
    raise ApiException(data['message'], data['status'])
hoshino.modules.pcrjjc2-clanbattle.pcrclient.ApiException: 发生了错误(E)。\n回到标题界面。
[2023-12-24 12:56:27,557 nonebot] INFO: Message -1146330721 is ignored: Handled by Hoshino
[2023-12-24 12:56:27,557] INFO in message: Message -1146330721 is ignored: Handled by Hoshino

是 bcr 那里的 api 改了吗？

**Comment by AddOneSecondL** [comment]
pcrclient.py 注释掉 await self.callapi('/check/check_agreement', {})

**Comment by TsaiDuck** [comment]
解决了，谢谢大佬！
